# Generated by Django 5.0.6 on 2024-07-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='placedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLACE', models.CharField(blank=True, max_length=100, null=True)),
                ('PLACEIMAGE', models.ImageField(blank=True, null=True, upload_to='placeimages')),
                ('DESCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
