# Generated by Django 5.0.6 on 2024-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOTELNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('HOTELIMAGE', models.ImageField(blank=True, null=True, upload_to='')),
                ('HOTELPRICE', models.IntegerField(blank=True, max_length=100, null=True)),
                ('HOTELDESCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('HOTELLOCATION', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
