# Generated by Django 5.0.6 on 2024-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_hoteldb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldb',
            name='HOTELIMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='hotelimages'),
        ),
        migrations.AlterField(
            model_name='hoteldb',
            name='HOTELPRICE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
