# Generated by Django 5.0.6 on 2024-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_hoteldb_hotelimage_alter_hoteldb_hotelprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldb',
            name='HOTELPLACE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
