# Generated by Django 5.0.6 on 2024-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_hoteldb_hotelplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomtypedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOMTYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('ROOMIMAGE', models.ImageField(blank=True, null=True, upload_to='roomtypeimages')),
                ('DESCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='hoteldb',
        ),
        migrations.DeleteModel(
            name='placedb',
        ),
    ]
