# Generated by Django 5.0.6 on 2024-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_rename_roomimage_roomtypedb_roomtypeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOMTYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('ROOMNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('ROOMIMAGE', models.ImageField(blank=True, null=True, upload_to='roomimages')),
                ('ROOMPRICE', models.IntegerField(blank=True, null=True)),
                ('ROOMDESCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
