# Generated by Django 5.0.6 on 2024-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_hoteldb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldb',
            name='ROOMIMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='roomimage'),
        ),
    ]
