# Generated by Django 5.0.6 on 2024-07-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_remove_roomnamedb_roomimage_roomnamedb_roomimage1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomnamedb',
            name='ROOMIMAGE1',
        ),
        migrations.RemoveField(
            model_name='roomnamedb',
            name='ROOMIMAGE2',
        ),
        migrations.AddField(
            model_name='roomnamedb',
            name='ROOMIMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='roomimage'),
        ),
    ]
