# Generated by Django 6.0 on 2026-01-15 05:28

from django.db import migrations, models
import django.db.models.deletion


def migrate_data(apps, schema_editor):
    """Populate FK field from CharField values"""
    RoomNameDB = apps.get_model('Backend', 'roomnamedb')
    RoomTypeDB = apps.get_model('Backend', 'roomtypedb')
    
    for room in RoomNameDB.objects.all():
        if room.ROOMTYPE:
            rt = RoomTypeDB.objects.filter(ROOMTYPE__iexact=room.ROOMTYPE).first()
            if rt:
                room.ROOMTYPE_FK_id = rt.id
                room.save(update_fields=['ROOMTYPE_FK_id'])


def reverse_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_remove_roomnamedb_roomimage1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomnamedb',
            name='ROOMTYPE_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Backend.roomtypedb'),
        ),
        migrations.RunPython(migrate_data, reverse_data),
    ]
