# Generated by Django 6.0 on 2026-01-15 05:29

from django.db import migrations, models
import django.db.models.deletion


def copy_data(apps, schema_editor):
    """Copy data from ROOMTYPE CharField to ROOMTYPE_FK ForeignKey"""
    RoomNameDB = apps.get_model('Backend', 'roomnamedb')
    RoomTypeDB = apps.get_model('Backend', 'roomtypedb')
    
    for room in RoomNameDB.objects.all():
        if room.ROOMTYPE_FK_id is None and room.ROOMTYPE:
            rt = RoomTypeDB.objects.filter(ROOMTYPE__iexact=room.ROOMTYPE).first()
            if rt:
                room.ROOMTYPE_FK = rt
                room.save(update_fields=['ROOMTYPE_FK_id'])


def reverse_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_add_roomtype_fk_field'),
    ]

    operations = [
        migrations.RunPython(copy_data, reverse_copy),
        migrations.RemoveField(
            model_name='roomnamedb',
            name='ROOMTYPE',
        ),
        migrations.RenameField(
            model_name='roomnamedb',
            old_name='ROOMTYPE_FK',
            new_name='ROOMTYPE',
        ),
    ]
