# Generated by Django 6.0 on 2026-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_replace_roomtype_with_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('query_type', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('room', 'Room Query'), ('staff', 'Staff Query'), ('booking', 'Booking Query'), ('general', 'General Query')], max_length=20)),
                ('keyword', models.CharField(help_text='Keywords to match (comma-separated)', max_length=200)),
                ('response', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('booking', 'Booking Confirmation'), ('cancellation', 'Booking Cancelled'), ('availability', 'Room Available'), ('price_drop', 'Price Drop'), ('system', 'System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='Backend_not_usernam_4bb5d7_idx'), models.Index(fields=['is_read', 'username'], name='Backend_not_is_read_fcb137_idx')],
            },
        ),
    ]
