# Generated by Django 5.0.6 on 2024-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontactdb',
            old_name='CUSTOMEREMAIL',
            new_name='CONTACTEMAIL',
        ),
        migrations.RenameField(
            model_name='customercontactdb',
            old_name='CUSTOMERMESSAGE',
            new_name='CONTACTMESSAGE',
        ),
        migrations.RenameField(
            model_name='customercontactdb',
            old_name='CUSTOMERNAME',
            new_name='CONTACTNAME',
        ),
        migrations.RemoveField(
            model_name='customercontactdb',
            name='CUSTOMERSUBJECT',
        ),
        migrations.AddField(
            model_name='customercontactdb',
            name='CONTACTNUMBER',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customercontactdb',
            name='CONTACTSUBJECT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
