# Generated by Django 5.0.6 on 2024-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_customeremail_customercontactdb_contactemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CONTACTEMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('CHECKIN', models.CharField(blank=True, max_length=100, null=True)),
                ('CHECKOUT', models.CharField(blank=True, max_length=100, null=True)),
                ('TOTALADULTS', models.CharField(blank=True, max_length=100, null=True)),
                ('TOTALCHILDS', models.IntegerField(blank=True, max_length=100, null=True)),
                ('ROOMNUMBER', models.CharField(blank=True, max_length=100, null=True)),
                ('SPECIALREQUEST', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
