# Generated by Django 5.0.6 on 2024-07-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_bookingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='CHECKIN',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='CHECKOUT',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
