# Generated by Django 5.0.6 on 2024-07-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_bookingdb_checkin_alter_bookingdb_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdb',
            old_name='ROOMNUMBER',
            new_name='SELECTROOM',
        ),
    ]
