# Generated by Django 5.0.6 on 2024-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_roomnumber_bookingdb_selectroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='CHECKIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='CHECKOUT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
