# Generated by Django 5.0.6 on 2024-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_bookingdb_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=100, null=True)),
                ('CONFIRMPASSWORD', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
