# Generated by Django 5.0.6 on 2024-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('ROOMNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PRICE', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
