# Generated by Django 5.0.6 on 2024-07-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_cartdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdb',
        ),
    ]
