# Generated by Django 6.0 on 2026-01-15 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_remove_roomnamedb_roomimage1_and_more'),
        ('webapp', '0011_totaldb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='CUSTOMER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='webapp.registerdb'),
        ),
        migrations.AddField(
            model_name='totaldb',
            name='BOOKING',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='webapp.bookingdb'),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='CHECKIN',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='CHECKOUT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='SELECTROOM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Backend.roomnamedb'),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='SPECIALREQUEST',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='TOTALADULTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='TOTALCHILDS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customercontactdb',
            name='CONTACTMESSAGE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customercontactdb',
            name='CONTACTNUMBER',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customercontactdb',
            name='CONTACTSUBJECT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='totaldb',
            name='MOBILE',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
